projects:
  whatsapp:
    schemaPath: amplify/backend/api/whatsapp/build/schema.graphql
    includes:
      - 'y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: ap-south-1
        apiId: null
        maxDepth: 3
